version: "3.7"

services:
  perf-backend-testing:
    #container_name: "perf-backend-testing-${GIT_BRANCH}"
    # add the code and build container
    build:
      context: ./service_backend
      dockerfile: Dockerfile.jepl
      args:
        - CICD_IMAGE=${dockerhub_cicd_backend} # cicd_backend_tag defined in the Jenkinsfile

# Have to execute all tests in the container, user conflict in case mounted: 
# - to write in the system root required
# - to run test, pg_ctl: cannot be run as root

