# Docker image for running CI/CD tests of the backend using JePL
ARG CICD_TAG=backend-1.0.1
FROM eoscperf/cicd-images:${CICD_TAG}

COPY backend backend
COPY autoapp.py ./
COPY requirements requirements
COPY factories factories
COPY tests tests
# package installation is described in tox.ini
COPY tox.ini tox.ini

ENV FLASK_ENV="production"

# to be on the save side, install dependencies
#RUN pip install --no-cache -r requirements/prod.txt
#RUN pip install --no-cache -r requirements/dev.txt


