# Docker image for running CI/CD tests of the frontend using JePL
FROM node:latest

ARG USER_ID=1000
ARG USER_GROUP=1000

# User ID and GROUP have to match Jenkins CI/CD User!
RUN groupadd -g ${USER_GROUP} jpltest
RUN useradd -u ${USER_ID} -g ${USER_GROUP} -m jpltest
USER jpltest

CMD ["tail","-f","/dev/null"]
