config:
  node_agent: 'docker_compose'
  deploy_template: '.sqa-frontend/docker-compose.yml'
#  project_repos:
#    eosc-perf:
#      repo: 'https://github.com/EOSC-synergy/eosc-perf.git'
#      branch: 'frontend'

environment:
  JPL_DOCKERFORCEBUILD: 'true'
  LANG: C.UTF-8

sqa_criteria:
  qc_style:
    repos:
      eosc-perf-frontend:
        container: perf-frontend-testing
        commands: 
        #- bash -c "cd /perf-frontend-testing && npm ci && ./node_modules/.bin/eslint ./ -f html -o eslint-codestyle.html"
        - bash -c "cd /perf-frontend-testing && npm ci && ./node_modules/.bin/eslint ./ -f stylish"
  qc_coverage:
    repos:
      eosc-perf-frontend:
        container: perf-frontend-testing
        commands:
        - bash -c "cd /perf-frontend-testing && npm test -- --verbose"
  qc_security:
    repos:
      eosc-perf-frontend:
        container: perf-frontend-testing
        commands:
        - bash -c "cd /perf-frontend-testing && npm audit"

timeout: 900

