version: "3.7"

services:
  perf-frontend-testing:
    image: "node:latest"
    # node image has 'node' user, Cypress seems only to work with non-root!
    user: node:node
    # add the code and build container
    volumes:
     - type: bind
       source: ./
       target: /perf-testing
    # to avoid shutting down the container
    command: ["tail","-f","/dev/null"]

  perf-frontend:
     build:
        context: "./service_frontend"
        dockerfile: "Dockerfile"
     image: "perf/perf-frontend"
