version: "3.7"

services:
  perf-frontend-testing:
    build:
      context: ./service_frontend
      dockerfile: Dockerfile.cicd
      args:
        USER_ID: ${jenkins_user_id}
        USER_GROUP: ${jenkins_user_group}
    # add the code and build container
    volumes:
     - type: bind
       source: ./
       target: /perf-testing
    # to avoid shutting down the container
    command: ["tail","-f","/dev/null"]

  perf-frontend:
     build:
        context: "./service_frontend"
        dockerfile: "Dockerfile"
     image: "perf/perf-frontend"
