"""empty message

Revision ID: 3b7a95bb6d22
Revises: 
Create Date: 2021-08-18 14:04:12.376067

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3b7a95bb6d22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_association',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('discriminator', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sub', sa.Text(), nullable=False),
    sa.Column('iss', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('sub', 'iss'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('sub', 'iss')
    )
    op.create_table('benchmark',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_sub', sa.Text(), nullable=False),
    sa.Column('creator_iss', sa.Text(), nullable=False),
    sa.Column('docker_image', sa.Text(), nullable=False),
    sa.Column('docker_tag', sa.Text(), nullable=False),
    sa.Column('json_schema', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_report_association_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['_report_association_id'], ['report_association.id'], ),
    sa.ForeignKeyConstraint(['creator_iss', 'creator_sub'], ['user.iss', 'user.sub'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('docker_image', 'docker_tag')
    )
    op.create_table('report',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_sub', sa.Text(), nullable=False),
    sa.Column('creator_iss', sa.Text(), nullable=False),
    sa.Column('verdict', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('_association_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.ForeignKeyConstraint(['_association_id'], ['report_association.id'], ),
    sa.ForeignKeyConstraint(['creator_iss', 'creator_sub'], ['user.iss', 'user.sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_sub', sa.Text(), nullable=False),
    sa.Column('creator_iss', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('_report_association_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['_report_association_id'], ['report_association.id'], ),
    sa.ForeignKeyConstraint(['creator_iss', 'creator_sub'], ['user.iss', 'user.sub'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('flavor',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_sub', sa.Text(), nullable=False),
    sa.Column('creator_iss', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('site_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('_report_association_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['_report_association_id'], ['report_association.id'], ),
    sa.ForeignKeyConstraint(['creator_iss', 'creator_sub'], ['user.iss', 'user.sub'], ),
    sa.ForeignKeyConstraint(['site_id'], ['site.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'name')
    )
    op.create_table('result',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('creator_sub', sa.Text(), nullable=False),
    sa.Column('creator_iss', sa.Text(), nullable=False),
    sa.Column('json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('_benchmark_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('_site_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('_flavor_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('_report_association_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['_benchmark_id'], ['benchmark.id'], ),
    sa.ForeignKeyConstraint(['_flavor_id'], ['flavor.id'], ),
    sa.ForeignKeyConstraint(['_report_association_id'], ['report_association.id'], ),
    sa.ForeignKeyConstraint(['_site_id'], ['site.id'], ),
    sa.ForeignKeyConstraint(['creator_iss', 'creator_sub'], ['user.iss', 'user.sub'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('result_tags',
    sa.Column('result_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('tag_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['result_id'], ['result.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('result_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_tags')
    op.drop_table('result')
    op.drop_table('flavor')
    op.drop_table('site')
    op.drop_table('report')
    op.drop_table('benchmark')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('report_association')
    # ### end Alembic commands ###
